version: "3.4"
services:
  database:
    image: postgres:latest
    ports:
      - '5434:5432'
    restart: always
    volumes:
      - ./backend/db-api:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rover
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    networks:
      - rover-network

  backend:
    environment:
      DATABASE_URL: "postgresql://pguser:pgpassword@database:5432/rover?schema=public"
      FRONT_URL: "http://localhost:3000"
      PORT: 3001
    build:
      context: ./backend
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - database
    networks:
      - rover-network

  frontend:
    environment:
      URL_BASE_API: http://backend:3001
    build:
      context: ./frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend
    networks:
      - rover-network

volumes:
  db-api:

networks:
  rover-network:
    name: rover-network
    external: false